spring.application.name=portfolio-backend
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=root
spring.datasource.password=dibyajit1234

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update